### ISSUE TITLE
scrolling text visible on fix header

### ISSUE THREAD

**Issue by galastur** [Shira-3749/jquery-scrollfix#3]
Hi Shira,

I love the scrollfix, so quick and easy to set up. 

Just one question. I have set my header as follows   $('.div-header').scrollFix();

so it will always be visible when scrolling down the page, however the text is visible in the header. Is there a way to fix this?

Thanks!

**Comment by shira-374** [comment]
Hi. What text do you mean? If you mean the content behind the fixed header, consider adding some background to the header.

Example:

``` css
.div-header.scroll-fix {
    background: yellow;
}
```

**Comment by galastur** [comment]
Hi Shira,

Thanks for you prompt reply and sorry for not being clear...but yes, that is exactly what I meant!...I have double checked now using a color as i was using an image background... 

``` html
.div-header
{
    height: 65px;
    background-image:url('images/banner.jpg');
}
```

I still have the same problem...however after observing what i was able to see underneath the banner the problem appears to lie with TinyMCE editor. I will explain myself..

Simple layout...banner at the top, an a table,which has some editable cells.

So the yellow cell i cannot see through the banner:

``` html
<td class="td-highlight">&nbsp;</td>
```

But the text on this one which uses TinyMCE can be seen.

``` html
<td><div class="notes-editable"> @Html.Raw(HttpUtility.HtmlDecode(t.Notes))</div></td>
```

So, it is the text on those "editable" cells that I can see through the banner as I scroll down

**Comment by shira-374** [comment]
This looks like a `z-index` issue. Try setting it on the fixed header. It should be higher than the one of the element that is overlapping it.

``` css
.div-header.scroll-fix {
    z-index: 10000; /* just an example */
}
```

**Comment by galastur** [comment]
Thanks Shira! spot on!

**Comment by shira-374** [comment]
No problem!
