### ISSUE TITLE
Can't work in iframe, need to scroll to see the effect

### ISSUE THREAD

**Issue by apchenjun** [Shira-3749/jquery-scrollfix#5]
Can't work in iframe, need to scroll to see the effect

**Comment by shira-374** [comment]
Do you have an example?

**Comment by apchenjun** [comment]
I found the problem，The div on my page is shown and hidden by code settings
I set style="display:none" by default. So there will be a scroll after the page is displayed to see the effect.
`<div class="form-group col-md-12 navbar-wrapper1 text-right" data-bind="visible:pageModel.status()!=1 || pageModel.status()!=3 "  style="display:none">
                    <button type="button" class="btn waves-effect waves-light btn-lg btn-rounded btn-primary" data-bind="click:submit">
                        save
                    </button>
                </div>`
![effect](https://user-images.githubusercontent.com/4964551/63819399-c8e12400-c977-11e9-84a2-4f8b68129ddf.gif)

**Comment by shira-374** [comment]
The fixed elements are only updated on scroll and when the window is resized. If the document is modified dynamically, you might need to call `pulse()` yourself.

Below is an example with [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver) (note that it's only supported in Chrome, you might need a polyfill for other browsers).

```js
var watcher = new Shira.ScrollFix.Watcher($('#some-element')[0], {
    // options
});

watcher.attach();

// update fixed elements when document.body is resized
var resizeObserver = new ResizeObserver(function () { watcher.pulse(); });
resizeObserver.observe(document.body);
```

I might integrate this into the plugin later, when `ResizeObserver` is more widely supported.

**Comment by shira-374** [comment]
Also, calling `$(...).scrollFix()` on invisible elements is not really supported. It should be delayed until they are visible.

**Comment by apchenjun** [comment]
@ShiraNai7 Thank you for your answer ，I am now removing style="display:none"， Solved the problem。
